name: simbolos_nacionales_ult
description: "UNA APLICACIÓN PARA CONOCER Y ESTUDIAR LOS SÍMBOLOS Y ATRIBUTOS PATRIOS"
publish_to: "none"
version: 1.7.7

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path: any
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite_common_ffi: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
